import type { Category } from "@/lib/types";

/**
 * Categories (TZ 3.3). Created as data, not hard-coded. Each category
 * gets its own indexable page with an SEO intro (TZ 5.3: no empty pages
 * made only of cards). Adding a category is adding an entry here.
 */
export const categories: Category[] = [
  // ---- art ----
  {
    slug: "painters",
    name: "Painters",
    direction: "art",
    shortDescription: "Painters working in oil, acrylic, watercolour and mixed media.",
    professions:
      "Oil, acrylic, watercolour, gouache, mixed media, portraits, landscapes, still life, abstract painting, murals, facades, interiors, decorative panels",
    seoText:
      "Looking for a painting created with real paint rather than generated by AI? This is where to look. Paint has a physical presence. Brushstrokes build up in layers, the canvas shows through, and the surface changes over time. What hangs on your wall is not a file, it is a real object that continues to live long after the artist puts the brushes away.",
    seoTitle: "Painters: original human-made painting",
    seoDescription:
      "Find painters who work by hand in oil, acrylic and watercolour. Buy originals or commission directly from the artist.",
  },
  {
    slug: "sculptors",
    name: "Sculptors",
    direction: "art",
    shortDescription: "Sculptors working in clay, stone, metal and wood.",
    professions:
      "Clay, wood, stone, metal, plaster, portrait sculpture, monumental sculpture, interior sculpture, contemporary forms, figurines, miniatures",
    seoText:
      "Looking for sculpture shaped or carved by hand rather than printed from a generated model? This is the place. A sculptor works with a material that pushes back. Stone splits along its own lines, wood follows the grain, and clay settles under its own weight. The finished sculpture grows out of that conversation with the material.",
    seoTitle: "Sculptors: human-made sculpture in clay, stone and metal",
    seoDescription:
      "Directory of sculptors working by hand in clay, stone, wood and metal. Commission or buy sculpture directly from the artist.",
  },
  {
    slug: "illustrators",
    name: "Illustrators",
    direction: "art",
    shortDescription: "Illustrators who draw by hand across styles and media.",
    professions:
      "Book illustration, children's books, covers, educational illustration, advertising illustration, packaging, websites, magazines, social media, character design, mascots",
    seoText:
      "Looking for original illustrations drawn from scratch rather than generated by AI? This is where to look. An illustration does more than repeat the text, it helps the reader see it. The artist chooses which moment to show, what to leave unseen, and where the eye should rest. That comes from understanding the story, not from writing a prompt.",
    seoTitle: "Illustrators: human-made, hand-drawn illustration",
    seoDescription:
      "Find illustrators who draw by hand, without AI. Browse human-made illustration and commission each artist directly.",
  },
  {
    slug: "concept-artists",
    name: "Concept Artists",
    direction: "art",
    shortDescription: "Concept artists designing characters, creatures and worlds.",
    professions:
      "Character concepts, environments, locations, vehicles, props, visual development for games, films and animation",
    seoText:
      "Looking for concept art for a character, environment, or prop for games, films, or animation, created by an artist rather than generated? This is where to look. Concept art is not just a beautiful image, it is a working document. Modelers build from it, environments grow from it, and countless creative decisions depend on it. A strong concept does more than show a world, it explains why that world works the way it does.",
    seoTitle: "Concept Artists: human character, creature and world design",
    seoDescription:
      "Directory of concept artists who design characters, creatures and environments by hand, without AI. Commission each artist directly.",
  },
  // ---- literature ----
  {
    slug: "fiction-authors",
    name: "Fiction Authors",
    direction: "literature",
    shortDescription: "Novelists and short-story writers.",
    professions:
      "Novels, novellas, short stories, crime, science fiction, historical fiction, commissioned books, ghostwriting, manuscript development",
    seoText:
      "Looking for prose written by a real author rather than generated by AI? This is where to look. A novel works because its author knows more about the characters than the reader is told. That unspoken layer is what keeps people turning pages. A generator can assemble sentences, but it has nothing to leave between the lines.",
    seoTitle: "Fiction Authors: human-written novels and short stories",
    seoDescription:
      "Directory of novelists and short-story writers who write without AI. Find human-written fiction and contact each author directly.",
  },
  {
    slug: "non-fiction-authors",
    name: "Non-Fiction Authors",
    direction: "literature",
    shortDescription: "Authors of research, memoir, history and practical books.",
    professions:
      "Business books, expert books, biographies, memoirs, history, psychology, popular science, turning experience into a book",
    seoText:
      "Need a book about something you know from the inside, written by a person rather than generated? Start here. Good non-fiction is judged by trust, not by polish. A real author stands behind every fact, knows where it came from, and understands the difference between evidence and repetition.",
    seoTitle: "Non-Fiction Authors: human-written research, history and memoir",
    seoDescription:
      "Directory of non-fiction authors who research and write without AI. Find human-written books and contact each author directly.",
  },
  {
    slug: "childrens-authors",
    name: "Children's Authors",
    direction: "literature",
    shortDescription: "Writers of picture books and children's fiction.",
    professions:
      "Fairy tales, books for young children, young adult fiction, educational stories",
    seoText:
      "Looking for a children's book written by an author rather than generated? This is the place. Children are the most honest readers in the world. If they are bored, they simply close the book. An author who has read the story aloud to real children knows things about that story that no generator ever will.",
    seoTitle: "Children's Authors: human-written picture books and children's fiction",
    seoDescription:
      "Directory of children's authors who write without AI. Find human-written picture books and children's fiction, and contact each author directly.",
  },
  {
    slug: "poets",
    name: "Poets",
    direction: "literature",
    shortDescription: "Poets writing and publishing their own work.",
    professions:
      "Lyric poetry, poetry collections, children's poetry, occasional verse, commercial verse, song lyrics",
    seoText:
      "Looking for poetry written by a poet rather than generated from a pattern? Start here. Poetry is carried as much by sound as by meaning. A pause, a broken rhythm, or an unexpected rhyme can say more than an entire stanza. Those choices come from the need to say something in exactly that way, not from statistical prediction.",
    seoTitle: "Poets: human-written poetry and verse",
    seoDescription:
      "Directory of poets who write without AI. Read and commission human-written poetry directly from the author.",
  },
  // ---- graphics-and-design ----
  {
    slug: "graphic-designers",
    name: "Graphic Designers",
    direction: "graphics-and-design",
    shortDescription: "Graphic designers for identity, print and packaging.",
    professions:
      "Brand identity, logos, colour systems, typography, brand guidelines, banners, posters, brochures, presentations, outdoor advertising, print, catalogues, magazines, menus, business cards, packaging",
    seoText:
      "Need a logo, brand identity, packaging, or advertising materials created by a designer rather than assembled by a generator from other people's work? This is where to look. A logo is not a picture, it is a decision. It has to work equally well on a storefront, a business card, a package, and an app icon. That is why a good logo starts not with a generator, but with understanding where it will have to live.",
    seoTitle: "Graphic Designers: human identity, print and packaging design",
    seoDescription:
      "Directory of graphic designers who design without AI: identity, logos, packaging and print. Reach each designer directly.",
  },
  {
    slug: "ui-ux-designers",
    name: "UI/UX Designers",
    direction: "graphics-and-design",
    shortDescription: "Interface and experience designers for apps and sites.",
    professions:
      "Websites, corporate sites, online stores, landing pages, catalogues, mobile apps for iOS and Android, prototypes, SaaS platforms, user accounts, dashboards, internal systems, CRM",
    seoText:
      "Need an interface for a website, mobile app, or internal system thought through by a designer rather than assembled from a stock template? This is where to look. A beautiful screen and a usable screen are not the same thing. A good interface comes from a designer who notices exactly where someone paused, hesitated, or closed the page. Decisions like that cannot be averaged out of the internet.",
    seoTitle: "UI/UX Designers: human interface and product design",
    seoDescription:
      "Directory of UI/UX designers who design interfaces without AI. Find human-made product design and contact each designer directly.",
  },
  {
    slug: "3d-artists",
    name: "3D Artists",
    direction: "graphics-and-design",
    shortDescription: "3D modellers for games, print, product and animation.",
    professions:
      "3D characters, digital sculpting, environments, props, game assets, 3D animation, texturing, rendering for games, film, advertising and product visualisation",
    seoText:
      "Need a three-dimensional character, environment, or object created by an artist rather than a generator? This is where to look. A good model has to do more than look convincing. It has to deform correctly, texture properly, and perform in the engine. All of that is decided from the very first polygon, not added after generation.",
    seoTitle: "3D Artists: human 3D modelling for games, print and product",
    seoDescription:
      "Directory of 3D artists who model by hand, without AI. Find production-ready human-made 3D work and hire each artist directly.",
  },
  {
    slug: "3d-designers",
    name: "3D Designers",
    direction: "graphics-and-design",
    shortDescription: "Product and industrial 3D designers: parts, packaging, print-ready models.",
    professions:
      "Product design, industrial design, parts, assemblies, packaging, labels, technical visualisation, models for 3D printing and manufacturing",
    seoText:
      "Need a model of a product, a part, or packaging that will actually be manufactured rather than just shown in an image? This is where to look. A 3D designer is hired for a working product, not a pretty picture. Wall thickness, tolerances, material shrinkage, and manufacturing requirements are proven on the first physical part, not in the render.",
    seoTitle: "3D Designers: human product and industrial 3D design",
    seoDescription:
      "Directory of 3D designers who model products, parts and packaging by hand, without AI. Find manufacture-ready human-made 3D design and hire each designer directly.",
  },
  // ---- photo-and-video ----
  {
    slug: "photographers",
    name: "Photographers",
    direction: "photo-and-video",
    shortDescription: "Photographers shooting real people, products and events.",
    professions:
      "Portraits, personal, business and family photography, commercial product and catalogue shoots, architecture, interiors, real estate, hotels, restaurants, weddings, conferences, corporate events",
    seoText:
      "Looking for photographs of real people, products, or events taken by a photographer rather than generated by AI? This is where to look. A photograph preserves something that happened only once. A person, the light, an expression, a passing glance, a moment that can never be repeated. That is why a real photograph cannot be replaced by generated imagery.",
    seoTitle: "Photographers: human photography, real cameras",
    seoDescription:
      "Directory of photographers who shoot real work, without AI generation. Find human-made photography and book each photographer directly.",
  },
  {
    slug: "video-editors",
    name: "Video Editors",
    direction: "photo-and-video",
    shortDescription: "Editors cutting long-form, ads, Reels and Shorts.",
    professions:
      "Commercial editing, YouTube, social media, film, television, interviews, documentaries",
    seoText:
      "Need an advert, a film, an interview, or social media content edited by a person rather than an automatic tool? Start here. Editing is rhythm. The same scene cut two frames earlier or later can completely change how it feels. Decisions like that come from watching the entire story unfold, not from following a rule.",
    seoTitle: "Video Editors: human editing for YouTube, ads and short-form",
    seoDescription:
      "Directory of video editors who cut real footage without AI. Find human-made editing and book each editor directly.",
  },
  {
    slug: "motion-designers",
    name: "Motion & 2D Animators",
    direction: "photo-and-video",
    shortDescription: "Motion designers and frame-by-frame animators.",
    professions:
      "2D animation, hand-drawn animation, stop motion, character animation, explainers, titles, opening sequences, motion graphics",
    seoText:
      "Need animation, titles, an opening sequence, or an explainer created by an animator rather than generated? This is the place. Animation is built on weight and timing. An object has to move as if it has mass, and a character as if it has intention. Those details are crafted frame by frame, they cannot be generated in a single step.",
    seoTitle: "Motion & 2D Animators: human animation and motion design",
    seoDescription:
      "Directory of motion designers and 2D animators who animate by hand, without AI. Find human-made animation and hire each artist directly.",
  },
  {
    slug: "colourists",
    name: "Colourists",
    direction: "photo-and-video",
    shortDescription: "Colourists grading footage for film, ads and video.",
    professions:
      "Film and television colour grading, commercials, music videos, commercial video, YouTube content",
    seoText:
      "Looking for colour grading on a film, commercial, music video, or online content, done by a colourist rather than an automatic filter? This is where to look. Colour is not a setting, it is part of the story. It defines the time of day, the mood, and the atmosphere of a scene, shaping whether the audience believes what they see. Those choices come from someone who has watched the entire film and understands where every scene is leading.",
    seoTitle: "Colourists: human colour grading for film and video",
    seoDescription:
      "Directory of colourists who grade footage by hand. Find human-made colour work and book each colourist directly.",
  },
  // ---- writing-and-translation ----
  {
    slug: "copywriters",
    name: "Copywriters",
    direction: "writing-and-translation",
    shortDescription: "Copywriters for sales pages, ads and content.",
    professions:
      "Websites, landing pages, advertising, email campaigns, product descriptions, articles, blogs, interviews, social media, SEO content",
    seoText:
      "Need copy for a website, advertising campaign, or email sequence, written by someone who understands your business rather than generated by AI? This is where to look. Great copy does not begin with the first sentence, it begins with questions. What makes your business different? Why should someone choose you instead of a competitor? Until those answers are clear, the right words do not exist.",
    seoTitle: "Copywriters: human-written sales copy and content",
    seoDescription:
      "Directory of copywriters who write without AI. Find human-written copy with real judgement behind it and hire each writer directly.",
  },
  {
    slug: "editors",
    name: "Editors & Proofreaders",
    direction: "writing-and-translation",
    shortDescription: "Editors and proofreaders for manuscripts and copy.",
    professions:
      "Literary editing, books, manuscripts, commercial editing, academic editing, proofreading, spelling, punctuation, typography, consistency",
    seoText:
      "Looking for an editor or proofreader who will read your work closely and understand what the author is trying to achieve rather than simply run an automated check? This is where to look. Editors earn their place where a text is technically correct but still does not work. An argument falls apart, a chapter opens too early, or an important idea gets lost. Seeing that requires holding the entire work in mind and understanding what the author wanted the reader to experience.",
    seoTitle: "Editors & Proofreaders: human editing and proofreading",
    seoDescription:
      "Directory of editors and proofreaders who work by hand. Find human editing for manuscripts and copy, and hire each editor directly.",
  },
  {
    slug: "translators",
    name: "Translators",
    direction: "writing-and-translation",
    shortDescription: "Translators and localisers across language pairs.",
    professions:
      "Literary translation, business, legal, technical and medical translation, website translation, localisation of apps, games, books and advertising",
    seoText:
      "Looking for a translation created by someone who understands both languages and both cultures rather than a machine rendering? Start here. Translation begins where the dictionary ends. An idiom, a joke, or a polite expression cannot simply be translated, it has to be recreated for another language and another culture. That takes an understanding of people, not just words.",
    seoTitle: "Translators: human translation and localisation",
    seoDescription:
      "Directory of translators and localisers who translate without AI. Find human translation and hire each translator directly.",
  },
  {
    slug: "scriptwriters",
    name: "Scriptwriters",
    direction: "writing-and-translation",
    shortDescription: "Scriptwriters for film, video, games and quests.",
    professions:
      "Feature films, short films, commercials, corporate video, game narrative, quests, branching dialogue, plays, musicals, adaptations",
    seoText:
      "Looking for a script for film, video, games, or theatre written by a real writer rather than generated by AI? This is where to look. A script is a blueprint for time. Dialogue has to sound like real people, and every scene should end just before the audience is ready to move on. That instinct for pacing is learned in front of real audiences, not from training data.",
    seoTitle: "Scriptwriters: human scripts for film, video and games",
    seoDescription:
      "Directory of scriptwriters who write scripts and game narrative without AI. Find human-written story work and hire each writer directly.",
  },
  // ---- music-and-audio ----
  {
    slug: "voice-actors",
    name: "Voice Actors",
    direction: "music-and-audio",
    shortDescription: "Voice actors and narrators recording live.",
    professions:
      "Advertising, corporate video, audiobooks, documentaries, e-learning, telephone systems, dubbing for films, television, games and animation",
    seoText:
      "Looking for a real voice for advertising, audiobooks, or dubbing rather than speech synthesis? This is the place. Synthetic voices can pronounce words correctly. They still do not know when silence says more than speech. A voice actor understands what happens between the lines, and that is what listeners hear.",
    seoTitle: "Voice Actors: human voice-over and narration",
    seoDescription:
      "Directory of voice actors and narrators who record live, without synthetic voices. Book each actor directly.",
  },
  {
    slug: "composers",
    name: "Composers & Musicians",
    direction: "music-and-audio",
    shortDescription: "Composers and musicians writing and playing original work.",
    professions:
      "Film, advertising, games, theatre, podcasts, songwriting, melodies, jingles, arrangement, session musicians, studio recording, live performance",
    seoText:
      "Need music written and performed by a real person rather than generated by AI? This is where to look. Music lives in tiny imperfections. A note played slightly early, a brief pause, or a subtle change in tempo gives a performance life. Those are exactly the details that generative systems smooth away first.",
    seoTitle: "Composers & Musicians: human-written original music",
    seoDescription:
      "Directory of composers and musicians who write and play without AI generation. Commission original human-made music directly.",
  },
  {
    slug: "sound-designers",
    name: "Sound Designers",
    direction: "music-and-audio",
    shortDescription: "Sound designers creating custom effects and audio worlds.",
    professions:
      "Film, games, interface sounds, atmospheres, effects, soundscapes built from scratch",
    seoText:
      "Looking for sound for film, games, or advertising created by a sound designer rather than pulled from a stock library? Start here. Great sound is rarely recorded exactly as it appears on screen. It is built from many different sounds until the audience believes it is real. That illusion comes from experience and imagination, not from browsing a sound library.",
    seoTitle: "Sound Designers: human sound effects and audio design",
    seoDescription:
      "Directory of sound designers who create custom effects by hand. Find human-made sound design and book each specialist directly.",
  },
  {
    slug: "audio-engineers",
    name: "Audio Engineers",
    direction: "music-and-audio",
    shortDescription: "Engineers mixing, mastering and cleaning audio.",
    professions:
      "Studio recording, mixing, mastering, audio restoration, podcasts, video sound",
    seoText:
      "Looking for recording, mixing, or mastering handled by an audio engineer rather than automatic processing? This is the place. A mix is a decision about what the listener should hear first. Automatic tools try to make everything equally loud, while a real engineer shapes the balance so the important parts naturally stand out.",
    seoTitle: "Audio Engineers: human mixing, mastering and podcast editing",
    seoDescription:
      "Directory of audio engineers who mix and master by hand. Find human audio work and book each engineer directly.",
  },
  // ---- development-and-it ----
  {
    slug: "web-developers",
    name: "Web Developers",
    direction: "development-and-it",
    shortDescription: "Developers building sites, stores and web apps.",
    professions:
      "Frontend, HTML, CSS, JavaScript, React, Vue, backend, APIs, databases, integrations, full-stack, corporate sites, online stores, web services, internal applications",
    seoText:
      "Need a corporate website, online store, web service, or internal application built by a person rather than generated by AI? This is where to look. Code is written once and maintained for years. When something unusual comes up or an unexpected error appears, only a developer who understands why the system was built this way can solve it.",
    seoTitle: "Web Developers: human-written sites, stores and web apps",
    seoDescription:
      "Directory of web developers who write and answer for their own code. Find developers who understand and support what they build.",
  },
  {
    slug: "mobile-developers",
    name: "Mobile Developers",
    direction: "development-and-it",
    shortDescription: "Developers building iOS and Android applications.",
    professions:
      "iOS, Android, cross-platform apps, service integrations, app store publishing, post-launch support",
    seoText:
      "Need a mobile app for iOS or Android written by a developer rather than assembled by a generator? This is where to look. An app does not end on release day. New operating system versions arrive, store requirements change, third-party services stop working. All of that is fixed by someone who knows the app from the inside.",
    seoTitle: "Mobile Developers: human-written iOS and Android apps",
    seoDescription:
      "Directory of mobile developers who write and answer for their own code. Find developers who understand and support what they build.",
  },
  {
    slug: "game-developers",
    name: "Game Developers",
    direction: "development-and-it",
    shortDescription: "Developers programming game logic, physics and mechanics.",
    professions:
      "Game programming, gameplay mechanics, Unity, Unreal Engine, mobile games, PC games",
    seoText:
      "Need a game, or part of one, built by a developer rather than assembled from generated pieces? This is the place. Games live or die on feel. A jump has to have weight, a hit has to feel right, and a difference of just a few frames can decide whether someone keeps playing or quits. That balance is found through hundreds of manual adjustments, and no generator can tell you where it should be.",
    seoTitle: "Game Developers: human-written game logic and mechanics",
    seoDescription:
      "Directory of game developers who write and answer for their own code. Find developers who understand and support what they build.",
  },
  {
    slug: "automation-developers",
    name: "Scripts & Automation",
    direction: "development-and-it",
    shortDescription: "Developers building bots, parsers and automation.",
    professions:
      "Business process automation, service integration, bots, scripts, data processing, internal tools",
    seoText:
      "To automate repetitive work, connect services, or build a tool for a specific task, look here. Automation starts long before the first line of code. The most important exceptions are rarely written down, they exist only in the experience of the people doing the work every day.",
    seoTitle: "Scripts & Automation: human-written bots, parsers and integrations",
    seoDescription:
      "Directory of developers who build bots, parsers and automation by hand. Find developers who understand and support what they build.",
  },
  {
    slug: "code-auditors",
    name: "Code Audit & Security",
    direction: "development-and-it",
    shortDescription: "Specialists reviewing code for bugs and vulnerabilities.",
    professions:
      "Code review, bug hunting, architecture review, performance, security audit, vulnerability testing, website and application security",
    seoText:
      "Need someone to review code, find a bug, or assess the security of a project? This is where to look. A real audit is more than a checklist. The most serious problems usually hide where different parts of a system meet and where undocumented assumptions collide. Finding them takes someone who understands not just the code, but the thinking behind it.",
    seoTitle: "Code Audit & Security: human code review and bug hunting",
    seoDescription:
      "Directory of specialists who audit code by hand: bugs, vulnerabilities and rescue of broken projects. Contact each specialist directly.",
  },
  // ---- architecture-and-interiors ----
  {
    slug: "architects",
    name: "Architects",
    direction: "architecture-and-interiors",
    shortDescription: "Architects designing houses, extensions and public buildings.",
    professions:
      "Private houses, extensions and rebuilds, small public buildings, concept design, planning permission drawings, working drawings, site supervision, restoration of existing buildings",
    seoText:
      "Looking for an architect who designs a building rather than generates a picture of one? Start here. A house has to stand on a specific plot, in a specific climate, under specific rules, and every one of those constraints changes the design. A generated image knows none of them: it has no structure behind it, no sections, no drawings anyone can build from. An architect carries the project from the first sketch through the permission drawings to the finished building, and answers for every decision along the way. Each profile links straight to the architect's own site or portfolio.",
    seoTitle: "Architects: human building design, drawings and site supervision",
    seoDescription:
      "Directory of architects who design without AI: houses, extensions and public buildings. See real projects and contact each architect directly.",
  },
  {
    slug: "interior-designers",
    name: "Interior Designers",
    direction: "architecture-and-interiors",
    shortDescription: "Designers producing plans, layouts and material selection.",
    professions:
      "Homes, apartments, offices, restaurants, shops, hotels, concept and planning, material selection, site supervision, decoration",
    seoText:
      "Looking for an interior for a home, office, or restaurant designed by a professional rather than assembled from AI-generated images? This is where to look. A beautiful rendering and a comfortable space are not the same thing. Doors have to open properly, sockets have to be exactly where they are needed, and materials have to last for years. Those decisions are tested in real life, not on a screen.",
    seoTitle: "Interior Designers: human plans, layouts and material selection",
    seoDescription:
      "Directory of interior designers who design without AI. Find human-made plans and contact each designer directly.",
  },
  {
    slug: "landscape-designers",
    name: "Landscape Designers",
    direction: "architecture-and-interiors",
    shortDescription: "Designers planning gardens, plots and outdoor spaces.",
    professions:
      "Private gardens, terraces, public spaces, planting, plant selection, landscape lighting, long-term landscape planning",
    seoText:
      "Need a garden, terrace, or landscape designed by a professional rather than generated? Start here. A garden is one of the few projects that is judged years after it is finished. Trees grow, plants change, and the space slowly becomes what the designer imagined. Landscape design is about designing time as much as place.",
    seoTitle: "Landscape Designers: human garden and plot design",
    seoDescription:
      "Directory of landscape designers who plan real sites without AI. Find human-made landscape design and contact each designer directly.",
  },
  // ---- handmade-and-craft ----
  {
    slug: "craft-makers",
    name: "Craft Makers",
    direction: "handmade-and-craft",
    shortDescription: "Makers of ceramics, furniture, decor and objects.",
    professions:
      "Ceramics, woodworking, leather, textiles, glass, stained glass, handmade toys and dolls",
    seoText:
      "Looking for an object made by hand rather than mass-produced? This is where to look. Every handmade object carries the mark of its maker. A subtle irregularity, a living texture, or a decision made in the middle of the work makes each piece unique. That is something no generated object can reproduce.",
    seoTitle: "Craft Makers: handmade ceramics, furniture and decor",
    seoDescription:
      "Directory of makers producing handmade ceramics, furniture, glass and decor. Buy or commission directly from the maker.",
  },
  {
    slug: "accessory-makers",
    name: "Accessories & Jewellery",
    direction: "handmade-and-craft",
    shortDescription: "Makers of leather goods, bags and jewellery.",
    professions:
      "Jewellery, custom pieces, repair and restoration, leather, glass and other materials",
    seoText:
      "Looking for jewellery or accessories made by a craftsperson rather than mass-produced? Start here. Jewellery is made for a person, not for a shelf. Size, form, materials, and even a small engraving become part of someone's story. That is something no catalogue piece can ever replace.",
    seoTitle: "Accessories & Jewellery: handmade leather goods and jewellery",
    seoDescription:
      "Directory of makers producing handmade bags, leather goods and jewellery. Buy or commission directly from the maker.",
  },
  {
    slug: "clothing-designers",
    name: "Clothing Designers",
    direction: "handmade-and-craft",
    shortDescription: "Designers sewing bespoke clothing and custom pieces.",
    professions:
      "Womenswear, menswear, childrenswear, original collections, stage and historical costume, custom tailoring",
    seoText:
      "Looking for clothing made to your measurements or designed by its creator rather than mass-produced? This is where to look. Clothing is judged on a person, not on a mannequin. Fabric moves, the fit changes, and the final decisions are made during the fitting. No rendering can show how a garment will live with the person wearing it.",
    seoTitle: "Clothing Designers: bespoke tailoring and custom clothing",
    seoDescription:
      "Directory of clothing designers who sew and pattern by hand. Order bespoke and custom pieces directly from the designer.",
  },

  // ---- other ----
  {
    slug: "restoration",
    name: "Restoration",
    direction: "other",
    shortDescription: "Restorers of paintings, furniture, books and photographs.",
    professions:
      "Paintings, furniture, books, bindings, sculpture, textiles, photographs, documents, architectural decoration",
    seoText:
      "Need to restore a painting, book, piece of furniture, or historic photograph? This is where to look. Restoration is about preserving, not replacing. There is rarely a second chance, so every decision matters. The skill of a restorer lies as much in knowing what not to touch as in knowing what to repair.",
    seoTitle: "Restoration: human restorers of art, furniture and books",
    seoDescription:
      "Directory of restorers working by hand on paintings, furniture, books and photographs. See finished work and contact each workshop directly.",
  },
  {
    slug: "calligraphy",
    name: "Calligraphy & Lettering",
    direction: "other",
    shortDescription: "Calligraphers and hand-lettering artists.",
    professions:
      "Wedding and event calligraphy, certificates, awards, hand-lettered logos, packaging, lettering, custom type design",
    seoText:
      "Looking for lettering created by the hand of a calligrapher rather than typed or generated? This is the place. Calligraphy is movement captured on paper. The pressure of the pen, the speed of the hand, and the rhythm of writing remain visible in every stroke. That is why real calligraphy always feels alive, even long after the ink has dried.",
    seoTitle: "Calligraphy & Lettering: human calligraphers and letterers",
    seoDescription:
      "Directory of calligraphers and hand-lettering artists working by hand. Commission custom lettering directly from the artist.",
  },
];
