import type { Direction } from "@/lib/types";

/**
 * Directions (TZ 3.2). Four active on stage 1-2; the remaining six are
 * laid down but not active (built later without a rewrite). Each carries
 * one of the seven brand colours (TZ 5.5). Content is data, not code —
 * adding a direction is adding an entry here, no logic change.
 */
export const directions: Direction[] = [
  {
    slug: "art-and-illustration",
    name: "Art & Illustration",
    color: "art",
    active: true,
    shortDescription: "Illustrators, fine artists and hand-drawn work made by people.",
    seoText:
      "Find illustrators and fine artists whose work is made by hand, not generated by AI. This section of No AI Marketplace brings together people and studios who draw, paint and illustrate — from children's book art to editorial illustration and gallery painting. Every profile links straight to the creator's own portfolio or shop, where you can commission or buy directly.",
    seoTitle: "Art & Illustration — human-made illustrators and fine artists",
    seoDescription:
      "Directory of illustrators and fine artists who create by hand, without AI. Browse human-made art and go directly to each creator's portfolio.",
  },
  {
    slug: "writing-and-publishing",
    name: "Writing & Publishing",
    color: "writing",
    active: true,
    shortDescription: "Writers, editors and authors who write without AI.",
    seoText:
      "Discover writers, editors and authors who produce text by hand, without AI generation. This section gathers copywriters, book authors, editors and ghostwriters who can show the human process behind their work. Each profile points to the writer's own site or portfolio, where you can hire them directly.",
    seoTitle: "Writing & Publishing — human writers, editors and authors",
    seoDescription:
      "Directory of writers, editors and authors who write without AI. Find human-made text and contact each creator directly.",
  },
  {
    slug: "design-and-branding",
    name: "Design & Branding",
    color: "design",
    active: true,
    shortDescription: "Graphic designers, logo and brand studios made by people.",
    seoText:
      "Find graphic designers and branding studios whose work is designed by people, not AI tools. This section covers logo design, brand identity, packaging and graphic design from independent designers and studios who keep a human process at the centre. Every profile links to the designer's own website or portfolio.",
    seoTitle: "Design & Branding — human graphic designers and studios",
    seoDescription:
      "Directory of graphic designers and branding studios who design without AI. Browse human-made design and reach each studio directly.",
  },
  {
    slug: "photography-and-video",
    name: "Photography & Video",
    color: "photo",
    active: true,
    shortDescription: "Photographers and videographers capturing real work.",
    seoText:
      "Browse photographers and videographers who capture and edit real images, without AI generation. This section brings together portrait, product, event and documentary photographers, as well as videographers, whose work is made behind a real camera. Each profile links to the creator's own site or portfolio for direct booking.",
    seoTitle: "Photography & Video — human photographers and videographers",
    seoDescription:
      "Directory of photographers and videographers who shoot real work, without AI. Find human-made photography and book each creator directly.",
  },

  // ---- Reserved for the future (TZ 3.2): laid down, not active ----
  {
    slug: "music-and-audio",
    name: "Music & Audio",
    color: "music",
    active: false,
    shortDescription: "Musicians, composers and audio producers.",
  },
  {
    slug: "architecture-and-interiors",
    name: "Architecture & Interiors",
    color: "services",
    active: false,
    shortDescription: "Architects and interior designers.",
  },
  {
    slug: "handmade-and-craft",
    name: "Handmade & Craft",
    color: "craft",
    active: false,
    shortDescription: "Makers, crafters and handmade goods.",
  },
  {
    slug: "professional-services",
    name: "Professional Services",
    color: "services",
    active: false,
    shortDescription: "Consultants and specialists.",
  },
  {
    slug: "software-and-digital-products",
    name: "Software & Digital Products",
    color: "design",
    active: false,
    shortDescription: "Developers and digital product makers.",
  },
  {
    slug: "education-and-consulting",
    name: "Education & Consulting",
    color: "services",
    active: false,
    shortDescription: "Educators, coaches and consultants.",
  },
];
