import type { Direction } from "@/lib/types";

/**
 * Directions (TZ 3.2). Nine directions, all active. Seven of them follow
 * the industry-standard framing used by freelance marketplaces (work
 * area, not job title). Two — Art and Literature — are named after the
 * authors themselves, because the platform lists creators of original
 * work, not only service providers.
 *
 * Content is data, not code — adding a direction is adding an entry here.
 */
export const directions: Direction[] = [
  {
    slug: "art",
    name: "Art",
    color: "art",
    active: true,
    shortDescription: "Painters, sculptors, illustrators and concept artists.",
    seoText:
      "Find artists whose work is made by hand, not generated. This section of No AI Marketplace brings together painters, sculptors, illustrators and concept artists who can show the process behind the piece — sketches, studies, work in progress. Every profile links straight to the artist's own portfolio, gallery or shop, where you can commission or buy directly.",
    seoTitle: "Art — human artists, painters, sculptors and illustrators",
    seoDescription:
      "Directory of artists who create by hand, without AI. Browse human-made art and go directly to each artist's own portfolio or shop.",
  },
  {
    slug: "literature",
    name: "Literature",
    color: "lit",
    active: true,
    shortDescription: "Novelists, non-fiction authors, children's writers and poets.",
    seoText:
      "Discover authors who write their own books. This section gathers novelists, non-fiction writers, children's authors and poets whose manuscripts are written by hand, without AI generation. Each profile links to the author's own site, publisher page or shop, where you can read, buy or reach them directly.",
    seoTitle: "Literature — human authors, novelists and poets",
    seoDescription:
      "Directory of authors who write without AI: fiction, non-fiction, children's books and poetry. Find human-written books and contact each author directly.",
  },
  {
    slug: "graphics-and-design",
    name: "Graphics & Design",
    color: "design",
    active: true,
    shortDescription: "Graphic designers, brand studios, UI/UX and 3D artists.",
    seoText:
      "Find graphic designers and studios whose work is designed by people, not generated by a tool. This section covers brand identity, logos, packaging, interface design and 3D modelling from independent designers and studios who keep a human process at the centre and can walk you through every decision. Every profile links to the designer's own website or portfolio.",
    seoTitle: "Graphics & Design — human designers, brand studios and 3D artists",
    seoDescription:
      "Directory of graphic designers, brand studios, UI/UX and 3D artists who design without AI. Browse human-made design and reach each studio directly.",
  },
  {
    slug: "photo-and-video",
    name: "Photo & Video",
    color: "photo",
    active: true,
    shortDescription: "Photographers, video editors, animators and colourists.",
    seoText:
      "Browse photographers and video professionals who capture, cut and grade real footage, without AI generation. This section brings together portrait, product, event and documentary photographers, editors, motion and 2D animators, and colourists whose work is made behind a real camera and a real timeline. Each profile links to the creator's own site or portfolio for direct booking.",
    seoTitle: "Photo & Video — human photographers, editors and animators",
    seoDescription:
      "Directory of photographers, video editors, animators and colourists who work without AI. Find human-made photo and video and book each creator directly.",
  },
  {
    slug: "writing-and-translation",
    name: "Writing & Translation",
    color: "writing",
    active: true,
    shortDescription: "Copywriters, editors, translators and scriptwriters.",
    seoText:
      "Find copywriters, editors, translators and scriptwriters who produce text by hand, without AI generation. This section is for businesses and publishers who need writing with real judgement behind it: someone who understands the subject, defends the argument and answers for every line. Each profile points to the writer's own site or portfolio, where you can hire them directly.",
    seoTitle: "Writing & Translation — human copywriters, editors and translators",
    seoDescription:
      "Directory of copywriters, editors, translators and scriptwriters who write without AI. Find human-written text and contact each specialist directly.",
  },
  {
    slug: "music-and-audio",
    name: "Music & Audio",
    color: "music",
    active: true,
    shortDescription: "Composers, voice actors, sound designers and engineers.",
    seoText:
      "Find composers, voice actors, sound designers and audio engineers who play, sing, speak and mix for real, without AI generation. This section covers original scores and songs, live voice-over and dubbing, custom sound effects, mixing and podcast production. Every profile links to the creator's own site or portfolio for direct booking.",
    seoTitle: "Music & Audio — human composers, voice actors and sound designers",
    seoDescription:
      "Directory of composers, voice actors, sound designers and audio engineers who work without AI. Find human-made music and audio and book each creator directly.",
  },
  {
    slug: "development-and-it",
    name: "Development & IT",
    color: "code",
    active: true,
    shortDescription: "Web, mobile, game developers, automation and code audit.",
    seoText:
      "Find developers who write and answer for their own code. This section covers web and mobile development, game development, scripts and bots, and code audit — from people who design the architecture themselves, understand every line they ship and can fix what they built. If a generated project stopped working and nobody can explain why, this is where you look for someone who can. Each profile links to the developer's own site, repository or portfolio.",
    seoTitle: "Development & IT — human developers who answer for their code",
    seoDescription:
      "Directory of web, mobile and game developers who write their own code, without AI generation. Find developers who understand and support what they build.",
  },
  {
    slug: "architecture-and-interiors",
    name: "Architecture & Interiors",
    color: "services",
    active: true,
    shortDescription: "Interior designers and landscape architects.",
    seoText:
      "Find interior designers and landscape architects who draw real plans for real spaces. This section covers layouts, technical drawings, material selection and site design made by people who account for the actual building, climate and budget — where a generated mistake costs real money on site. Each profile links to the designer's own site or portfolio for direct contact.",
    seoTitle: "Architecture & Interiors — human interior and landscape designers",
    seoDescription:
      "Directory of interior designers and landscape architects who design without AI. Find human-made plans and contact each designer directly.",
  },
  {
    slug: "handmade-and-craft",
    name: "Handmade & Craft",
    color: "craft",
    active: true,
    shortDescription: "Makers, accessory designers and clothing designers.",
    seoText:
      "Browse makers who work with their hands. This section gathers craftspeople producing ceramics, furniture, decor, leather goods, jewellery and custom clothing — physical objects that cannot be generated, only made. Every profile links straight to the maker's own shop, where you can buy or commission directly.",
    seoTitle: "Handmade & Craft — human makers, accessories and clothing",
    seoDescription:
      "Directory of makers producing handmade goods: ceramics, furniture, leather, jewellery and custom clothing. Buy directly from each maker.",
  },
];
